/**
 * ============================================================================
 * AI SERVICE
 * ============================================================================
 *
 * Purpose:
 * --------
 * Acts as the central communication layer between the AI Engine and
 * the configured AI provider (currently Ollama).
 *
 * Responsibilities:
 * -----------------
 * • Receive fully prepared prompts.
 * • Send prompts to the selected AI provider.
 * • Return the generated response.
 * • Handle provider failures gracefully.
 *
 * Future Providers:
 * -----------------
 * • Ollama
 * • OpenAI
 * • Gemini
 * • Claude
 *
 * Author : Vivan Pandya
 * Project: Personal Portfolio AI Assistant
 * ============================================================================
 */

import { generateOllamaResponse } from "./ollama-client.js";
import { useFallbackResponse } from "./fallback.js";
import { AI_CONFIG } from "./api-config.js";
import { AI_PROVIDER } from "../utils/constants.js";
import { validatePrompt } from "../utils/validators.js";
import { logError, logInfo, logStage, logWarning } from "../utils/logger.js";

/**
 * Sends a prompt to the configured AI provider.
 *
 * @param {string} prompt - Final prompt generated by Prompt Builder.
 * @returns {Promise<string>} AI generated response.
 */
export async function generateAIResponse(prompt) {
    const startedAt = Date.now();

    try {

        validatePrompt(prompt);

        logStage("[AI SERVICE] Entering generateAIResponse", {
            inputType: typeof prompt,
            promptLength: prompt.length
        });

        logInfo("[AI SERVICE] Preparing provider request", {
            provider: AI_CONFIG.provider,
            model: AI_CONFIG.model,
            promptLength: prompt.length
        });

        let response = "";

        switch (AI_CONFIG.provider.toLowerCase()) {

            case AI_PROVIDER.OLLAMA:
                response = await generateOllamaResponse(prompt);
                break;

            default:
                throw new Error(
                    `Unsupported AI provider: ${AI_CONFIG.provider}`
                );
        }

        // Ensure a valid response exists
        if (!response || response.trim() === "") {
            throw new Error("AI returned an empty response.");
        }

        logInfo("[AI SERVICE] Provider response received", {
            provider: AI_CONFIG.provider,
            responseLength: response.length,
            preview: response.slice(0, 200),
            totalRequestTimeMs: Date.now() - startedAt
        });

        return response;

    } catch (error) {

        logError("[AI SERVICE] Provider request failed", {
            provider: AI_CONFIG.provider,
            model: AI_CONFIG.model,
            error: error instanceof Error ? error.message : String(error),
            stack: error instanceof Error ? error.stack : null,
            rawResponse: error?.rawResponse ?? null,
            responseBody: error?.responseBody ?? null
        });

        if (error?.name === "ProviderRequestError" || error?.name === "ProviderResponseError") {
            logWarning("[AI SERVICE] Falling back to default response", {
                reason: error.name,
                message: error.message
            });
            return useFallbackResponse();
        }

        throw error;
    }
}
